map = {
    "CanUpdateServer": "Update Server",
    "CanManageRoles": "Manage Roles",
    "CanInviteMembers": "Invite Members",
    "CanKickMembers": "Kick / Ban Members",
    "CanManageGroups": "Manage Groups",
    "CanManageChannels": "Manage Channels",
    "CanManageWebhooks": "Manage Webhooks",
    "CanMentionEveryone": "Can Mention @everyone and @here",
    "CanModerateChannels": "Access Moderator View",
    "CanBypassSlowMode": "Slowmode Exception",
    "CanReadApplications": "View Applications",
    "CanApproveApplications": "Approve Applications",
    "CanEditApplicationForm": "Edit Application Forms",
    "CanIndicateLfmInterest": "Indicate Find Players Interest",
    "CanModifyLfmStatus": "Modify Find Players Status",
    "CanReadAnnouncements": "View Announcements",
    "CanCreateAnnouncements": "Create and Remove Announcements",
    "CanManageAnnouncements": "Manage Announcements",
    "CanReadChats": "Read Messages",
    "CanCreateChats": "Send Messages",
    "CanUploadChatMedia": "Upload Media",
    "CanCreateThreads": "Create Threads",
    "CanCreateThreadMessages": "Send Messages in Threads",
    "CanCreatePrivateMessages": "Send Private Messages",
    "CanManageChats": "Manage Messages",
    "CanManageThreads": "Manage Threads",
    "CanCreateChatForms": "Create Polls and Forms",
    "CanReadEvents": "View Events",
    "CanCreateEvents": "Create Events",
    "CanEditEvents": "Manage Events",
    "CanDeleteEvents": "Remove Events",
    "CanEditEventRsvps": "Edit RSVPs",
    "CanReadForums": "Read Forums",
    "CanCreateTopics": "Create Forum Topics",
    "CanCreateTopicReplies": "Create Topic Replies",
    "CanDeleteTopics": "Manage Topics",
    "CanStickyTopics": "Sticky Topics",
    "CanLockTopics": "Lock Topics",
    "CanReadDocs": "View Docs",
    "CanCreateDocs": "Create Docs",
    "CanEditDocs": "Manage Docs",
    "CanDeleteDocs": "Remove Docs",
    "CanReadMedia": "See Media",
    "CanAddMedia": "Create Media",
    "CanEditMedia": "Manage Media",
    "CanDeleteMedia": "Remove Media",
    "CanListenVoice": "Hear Voice",
    "CanAddVoice": "Add Voice",
    "CanManageVoiceGroups": "Manage Voice Rooms",
    "CanAssignVoiceGroup": "Move Members",
    "CanDisconnectUsers": "Disconnect User",
    "CanBroadcastVoice": "Broadcast",
    "CanDirectVoice": "Whisper",
    "CanPrioritizeVoice": "Priority Speaker",
    "CanUseVoiceActivity": "Use Voice Activity",
    "CanMuteMembers": "Mute Members",
    "CanDeafenMembers": "Deafen Members",
    "CanSendVoiceMessages": "Send Messages in Voice Channel",
    "CanCreateScrims": "Create Scrims",
    "CanManageTournaments": "Manage Tournaments",
    "CanRegisterForTournaments": "Register for Tournaments",
    "CanManageEmotes": "Manage Emoji",
    "CanChangeNickname": "Change Nickname",
    "CanManageNicknames": "Manage Nicknames",
    "CanViewFormResponses": "View Form Responses",
    "CanViewPollResponses": "View Poll Results",
    "CanReadListItems": "View List Items",
    "CanCreateListItems": "Create List Items",
    "CanUpdateListItems": "Manage List Item Messages",
    "CanDeleteListItems": "Remove List Items",
    "CanCompleteListItems": "Complete List Items",
    "CanReorderListItems": "Reorder List Items",
    "CanViewBracket": "View Brackets",
    "CanReportScores": "Report Scores",
    "CanReadSchedules": "View Schedules",
    "CanCreateSchedule": "Create Schedule",
    "CanDeleteSchedule": "Delete Schedule",
    "CanManageBots": "Manage Bots",
    "CanManageServerXp": "Manage Server XP",
    "CanReadStreams": "View Streams",
    "CanJoinStreamVoice": "Join Voice in Streams",
    "CanCreateStreams": "Add Stream",
    "CanSendStreamMessages": "Send Messages in Streams",
    "CanAddStreamVoice": "Add Voice in Streams",
    "CanUseVoiceActivityInStream": "Use Voice Activity in Streams",
}
